[customizations.installer.kickstart]
contents = """
lang en_US.UTF-8
keyboard us
timezone CET

user --name demo --password demo123demo --plaintext --groups wheel
rootpw --lock
zerombr
clearpart --all --initlabel
autopart --noswap --type=lvm

%post
bootc switch --mutate-in-place --transport registry quay.io/fedora-ostree-desktops/kinoite:42
reboot --eject
%end

"""

[customizations.installer.modules]
enable = [
  "org.fedoraproject.Anaconda.Modules.Storage"
]
disable = [
  "org.fedoraproject.Anaconda.Modules.Subscription",
  "org.fedoraproject.Anaconda.Modules.Localization"
  #"org.fedoraproject.Anaconda.Modules.Network",
  #"org.fedoraproject.Anaconda.Modules.Security",
  #"org.fedoraproject.Anaconda.Modules.Services",
  #"org.fedoraproject.Anaconda.Modules.Users",
  #"org.fedoraproject.Anaconda.Modules.Timezone",
]

